language: go

os: linux
dist: bionic

go:
  - 1.15

services:
  - docker

install:
  - .travis/install_kernel_headers.sh
  #- onboarding/check_system.sh
  #- .travis/install_k8s.sh
  #- onboarding/check_k8s.sh

script:
  #- KubeArmor/build/test_kubearmor.sh
  - .travis/verify_image.sh
