language: go

os: linux
dist: bionic

go:
  - 1.15

services:
  - docker

install:
  - .travis/prepare.sh
  #- .travis/install_k8s.sh

script:
  #- .travis/check_k8s.sh
  #- .travis/test_kubearmor.sh
  - .travis/verify_image.sh
