apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kubearmor
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: kubearmor
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root-passwd
        - name: MYSQL_DATABASE
          value: kubearmor-db
        - name: MYSQL_USER
          value: kubearmor
        - name: MYSQL_PASSWORD
          value: kubearmor-passwd
        ports:
        - name: mysql-port
          containerPort: 3306
