apiVersion: v1
kind: Service
metadata:
  name: kubearmor-policy-manager-metrics-service
  namespace: kube-system
  labels:
    kubearmor-app: kubearmor-policy-manager
spec:
  selector:
    kubearmor-app: kubearmor-policy-manager
  ports:
  - name: https
    port: 8443
    targetPort: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-policy-manager
  namespace: kube-system
  labels:
    kubearmor-app: kubearmor-policy-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      kubearmor-app: kubearmor-policy-manager
  template:
    metadata:
      labels:
        kubearmor-app: kubearmor-policy-manager
      annotations:
        kubearmor-policy: audited
    spec:
      serviceAccountName: kubearmor
      containers:
      - name: kube-rbac-proxy
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        ports:
        - containerPort: 8443
          name: https
      - name: kubearmor-policy-manager
        image: kubearmor/kubearmor-policy-manager:latest
        args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
