apiVersion: apps/v1
kind: Pod
metadata:
  name: kubearmor-relay
  namespace: kube-system
  labels:
    deployment: kubearmor-relay
spec:
  selector:
    matchLabels:
      container: kubearmor-relay
  template:
    metadata:
      labels:
        container: kubearmor-relay
      annotations:
        kubearmor-policy: audited
    spec:
      serviceAccountName: {{.Values.kubearmor.serviceAccountName }}
      containers:
      - name: kubearmor
        image: "{{ .Values.kubearmor-relay.image.repository }}:{{ .Values.kubearmor-relay.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 32767
