apiVersion: v1
kind: Service
metadata:
  name: kubearmor
  namespace: kube-system
spec:
  selector:
    container: kubearmor-relay
  ports:
  - port: 32767
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubearmor-relay
  namespace: kube-system
  labels:
    deployment: kubearmor-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      container: kubearmor-relay
  template:
    metadata:
      labels:
        container: kubearmor-relay
    spec:
      serviceAccountName: kubearmor
      containers:
        - name: kubearmor-relay-server
          image: accuknox/kubearmor-relay-server:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 32767
