apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-wordpress-dir-audit
  namespace: wordpress-mysql
spec:
  severity: 3
  selector:
    matchLabels:
      app: wordpress
  file:
    matchDirectories:
    - dir: /var/www/html/
      recursive: true
  action:
    Audit
