apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-group-2-file-path-audit-from-source-path
  namespace: multiubuntu
spec:
  severity: 5
  message: "audit /bin/cat accessing /home/user1/secret_data1.txt"
  selector:
    matchLabels:
      group: group-2
  file:
    matchPaths:
      - path: /home/user1/secret_data1.txt # /bin/cat /home/user1/secret_data1.txt (no logs)
        fromSource: # /bin/head /home/secret_data1.txt (logs)
        - path: /bin/cat
  action:
    Audit
