apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-3-proc-path-owner-allow
  namespace: multiubuntu
spec:
  selector:
    matchLabels:
      container: ubuntu-3
  process:
    matchPaths:
    - path: /home/user1/hello
      ownerOnly: true
    - path: /bin/su # to change root to user1
  file:
    matchDirectories: # to change root to user1
    - dir: /etc/
      recursive: true
    - dir: /proc/
      recursive: true
    matchPaths: # to change root to user1
    - path: /run/utmp
  action:
    Allow
