apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-group-2-file-path-block-from-source-dir
  namespace: multiubuntu
spec:
  severity: 5
  message: "block /bin/* from accessing /home/user1/secret_data1.txt"
  selector:
    matchLabels:
      group: group-2
  file:
    matchPaths:
      - path: /home/user1/secret_data1.txt
        fromSource:
        - dir: /bin/
  action:
    Block
