apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-2-file-dir-recursive-audit-from-source-path
  namespace: multiubuntu
spec:
  severity: 10
  message: "a critical directory was accessed"
  tags:
  - WARNNING
  selector:
    matchLabels:
      container: ubuntu-2
  file:
    matchDirectories: 
    - dir: /credentials/ # cat /credentials/password (logs)
      recursive: true # head /credentials/keys/priv.key (no logs)
      fromSource: # head /credentials/password (no logs)
      - path: /bin/cat # cat /credentials/keys/priv.key (logs)
  action:
    Audit
