apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-3-file-dir-readonly-allow
  namespace: multiubuntu
spec:
  severity: 10
  message: "a critical directory was accessed"
  tags:
  - WARNNING
  selector:
    matchLabels:
      container: ubuntu-3
  process:
    matchDirectories:
    - dir: /bin/ # need some exectuables to test
  file:
    matchPaths:
    - path: /dev/tty
      readOnly: false
    matchDirectories: # echo "new password" > /credentials/password (permission denied) 
    - dir: /credentials/ # cat /credentials/password (success)
      readOnly: true # cat /credentials/keys/priv.key (permission denied)
    - dir: /dev/pts/
      recursive: true
  action:
    Allow
