apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-3-file-dir-readonly-audit
  namespace: multiubuntu
spec:
  severity: 10
  message: "a critical directory was accessed"
  tags:
  - WARNNING
  selector:
    matchLabels:
      container: ubuntu-3
  file:
    matchDirectories: # echo "new password" > /credentials/password (logs) 
    - dir: /credentials/ # cat /credentials/password (no logs)
      readOnly: true # cat /credentials/keys/priv.key (no logs)
  action:
    Audit
