apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-group-2-proc-path-audit
  namespace: multiubuntu
spec:
  severity: 4
  selector:
    matchLabels:
      group: group-2
  process:
    matchPaths:
    - path: /bin/sleep # try sleep 1
  action:
    Audit
