apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-5-file-dir-recursive-readonly-audit
  namespace: multiubuntu
spec:
  severity: 10
  message: "a critical directory was accessed"
  tags:
  - WARNNING
  selector:
    matchLabels:
      container: ubuntu-5
  file:
    matchDirectories: # cat /credentials/keys/priv.key (no logs)
    - dir: /credentials/ # cat /credentials/password (no logs)
      recursive: true # echo test >> /credentials/keys/priv.key (logs)
      readOnly: true # echo test >> /credentials/password (logs)
  action:
    Audit
