apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-group-2-file-path-owner-allow-from-source-path
  namespace: multiubuntu
spec:
  severity: 7
  selector:
    matchLabels:
      group: group-2
  process:
    matchDirectories:
    - dir: /bin/ # required to change root to user1 / try 'su - user1'
      recursive: true
    - dir: /usr/bin/ # used in changing accounts
      recursive: true
  file:
    matchPaths:
    - path: /home/user1/secret_data1.txt # su - user1 -c "head secret_data.txt" (permission denied) 
      ownerOnly: true # su - user1 -c "/bin/cat secret_data.txt" (success)
      fromSource:
      - path: /bin/cat # /bin/cat /home/user1/secret_data.txt (permission denied)
    - path: /run/utmp # required to change root to user1
    - path: /root/.bashrc # used by root
    - path: /home/user1/.profile # used by user1
    - path: /home/user1/.bashrc # used by user1
    matchDirectories:
    - dir: /etc/ # required to change root to user1 (coarse-grained way)
      recursive: true
    - dir: /proc/ # required to change root to user1 (coarse-grained way)
      recursive: true
  action:
    Allow
