apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-2-file-dir-owner-audit
  namespace: multiubuntu
spec:
  severity: 7
  selector:
    matchLabels:
      container: ubuntu-2
  file:
    matchDirectories:
    - dir: /home/user1/
      ownerOnly: true
  action:
    Audit
