apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-1-file-path-audit
  namespace: multiubuntu
spec:
  severity: 10
  message: "a critical file was accessed"
  tags:
  - WARNING
  selector:
    matchLabels:
      container: ubuntu-1
  file:
    matchPaths:
    - path: /etc/passwd # cat /etc/passwd
    - path: /secret.txt # echo "test" >> /secret.txt
    - path: /credentials/password # echo "test" >> /credentials/password
  action:
    Audit
