apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: reproduce-issue-353
  namespace: multiubuntu
spec:
  severity: 7
  message: "File accessed by non auth user"
  tags:
  - WARNING
  selector:
    matchLabels:
      container: ubuntu-4
  file:
    matchPaths:
    - path: /home/user1/secret_data1.txt
      ownerOnly: true
  action:
    Audit