apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubearmor-mysql-client
  namespace: kubearmor
  labels:
    app: kubearmor-mysql-client
spec:
  selector:
    matchLabels:
      app: kubearmor-mysql-client
  template:
    metadata:
      labels:
        app: kubearmor-mysql-client
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: kubearmor-mysql-client
        image: accuknox/kubearmor-mysql-client:latest
        env:
        - name: DB_HOST
          value: mysql.kubearmor.svc:3306
        - name: DB_NAME
          value: kubearmor-db
        - name: DB_USER
          value: kubearmor
        - name: DB_PASSWD
          value: kubearmor-passwd
        - name: TABLE_MSG
          value: messages
        - name: TABLE_ALERT
          value: alerts
        - name: TABLE_LOG
          value: syslogs
