apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kubearmor
spec:
  selector:
    app: elasticsearch
  ports:
  - name: es-9200
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: es-9300
    port: 9300
    targetPort: 9300
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-volume
  namespace: kubearmor
  labels:
    type: local
spec:
  storageClassName: elasticsearch-pv
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pv-claim
  namespace: kubearmor
spec:
  storageClassName: elasticsearch-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: kubearmor
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: fix-permissions
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        securityContext:
          privileged: true
        volumeMounts:
          - name: data-path
            mountPath: /data
      containers:
      - name: elasticsearch
        image: elastic/elasticsearch:6.8.6
        imagePullPolicy: Always
        securityContext:
          privileged: false
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        env:
        - name: CLUSTER_NAME
          value: "Default"
        - name: DISCOVERT_ZEN_MINIMUM_MASTER_NODES
          value: "1"
        - name: DISCOVERY_TYPE
          value: "single-node"
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        - name: XPACK_ML_ENABLED
          value: "false"
        - name: XPACK_GRAPH_ENABLED
          value: "false"
        - name: XPACK_WATCHER_ENABLED
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xmx256m -Xms256m
        volumeMounts:
        - name: data-path
          mountPath: /usr/share/elasticsearch/data
        ports:
        - containerPort: 9200
        - containerPort: 9300
      volumes:
      - name: data-path
        persistentVolumeClaim:
          claimName: elasticsearch-pv-claim

# max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
# sudo sysctl -w vm.max_map_count=262144
