# permissions for end users to edit kubearmormacros.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubearmormacro-editor-role
rules:
- apiGroups:
  - security.kubearmor.com
  resources:
  - kubearmormacros
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.kubearmor.com
  resources:
  - kubearmormacros/status
  verbs:
  - get
