name: ci-go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  go-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: v1.16

      - name: Check gofmt
        run: gofmt -s -d $(find . -type f -name '*.go' -print)
        working-directory: KubeArmor

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Run Revive Action by pulling pre-built image
        uses: morphy2k/revive-action@v2
        with:
          path: "./KubeArmor/..."

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: v1.16

      - name: Run Golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
          golangci-lint run
        working-directory: KubeArmor

  go-sec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: v1.16

      - name: Run Gosec Security Scanner
        run: |
          go get -u github.com/securego/gosec/v2/cmd/gosec
          gosec ./...
        working-directory: KubeArmor

  license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Check License Header
        uses: apache/skywalking-eyes@9bd5feb86b5817aa6072b008f9866a2c3bbc8587
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
