name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: go workflows
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Run GolangCI Lint
        if: ${{ always() }}
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: KubeArmor

      - uses: actions/setup-go@v2
        if: ${{ always() }}
        with:
          go-version: v1.16

      - name: Check gofmt
        if: ${{ always() }}
        run: gofmt -s -d $(find . -type f -name '*.go' -print)

      - name: Run Gosec Security Scanner
        run: |
          go get -u github.com/securego/gosec/v2/cmd/gosec
          gosec ./...
        working-directory: KubeArmor

