on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'main'

name: Latest version release after testing KubeArmor image

env: 
  TEST_TAG: kubearmor/kubearmor:latest

jobs:
  build:
    name: Create KubeArmor Release - 18.04
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout KubeArmor code
        uses: actions/checkout@v2

      - name: Generate KubeArmor artifacts
        run: GITHUB_SHA=$GITHUB_SHA ./KubeArmor/build/build_kubearmor.sh test

      - name: Setup Enviroment
        run: |        
          # create a single-node K3s cluster
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-backend=none --cluster-cidr=192.168.0.0/16 --disable-network-policy --disable=traefik" sh -

          #setting a variable environment
          mkdir ~/.kube/
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config 

          # install Calico-Operator
          kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

          # install Calico-Manifest
          kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
            
      - name: Run KubeArmor 
        run: |
          kubectl apply -f KubeArmor/build/kubearmor-test-k3s.yaml
          kubectl get pods --all-namespaces 

          while [[ $(kubectl get pods -l kubearmor-app=kubearmor -n kube-system -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done

          sleep 60

      - name: Run KubeArmor tests
        run: |
          ./tests/test-scenarios-github.sh

      - name: Archive log artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: kubearmor.logs
          path: |
            /tmp/kubearmor.test
            /tmp/kubearmor.log
            /tmp/kubearmor.msg
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Push KubeArmor images to Docker
        run: ./KubeArmor/build/push_kubearmor.sh latest
